[package]
name = "file_mapper"
version = "0.1.0"
authors = ["Michael Robbins <michael@dalmura.com.au>"]

[dependencies]
yaml-rust = "*"
getopts = "0.*.*"
flate2 = "0.*.*"
bzip2 = "0.*.*"
log = "0.*.*"
env_logger = "0.*.*"
csv = "0.*.*"
